### ISSUE TITLE
KiChain & TagRead

### ISSUE THREAD

**Issue by samosaman73** [Indirecta-Technologies/fosd#1]
If you have a TagRead card as a tool in KiChain, the TagRead reader will not read the value of the card.

**Comment by LolloDev5123** [comment]
As stated in private Discord Ticket-115 I believe:
- This issue is caused by TagRead itself
- It should be already patched in the latest TagRead version

I have tested this and the version I am using (which is the latest from github files) should work with any NFC Antenna including iComm and in-KiChain tags.

Would you mind checking:
- If other NFC cards work (like the default ones)
- If disabling `NFC_SAVEBANDWITH` makes NFC work
- Sending lines (207-212) of TagRead CORE Script

**Comment by samosaman73** [comment]
Hi, sorry for no response. This appears to have resolved itself.
